# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81dcb60ffa0697155d09eb5eb5f12927a62c62ac23f588cdf1a06383512107ee036e00cfc4f901eaed1da4141b0d0405af301aa3f08170f45fcadfa351509844

test:
  secret_key_base: 4162cfa5464c45b8cb96079638a69b768881f45eb08c4a789b87af5c754af00499cc03d426c05f4a494c17381e6baf8c4f5ca7e72aa6addaea273c66a7678b61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
